### ISSUE TITLE
RuboCop extension suggestion not easily applicable

### ISSUE THREAD

**Issue by Aqualon** [rubocop/rubocop-rspec_rails#28]
In a repo I work on I got the following suggestion of extensions
```
Tip: Based on detected gems, the following RuboCop extension libraries might be helpful:
  * rubocop-factory_bot (https://rubygems.org/gems/rubocop-factory_bot)
  * rubocop-rspec_rails (https://rubygems.org/gems/rubocop-rspec_rails)
```
If like for other rubocop extensions (we have `rubocop-performance` and `rubocop-rails`), I just add `rubocop-rspec_rails` to Gemfile and require it in `.rubocop.yml`, running rubocop fails with
```
cannot load such file -- rubocop/rspec/language/node_pattern
```

After reading the README, that was caused by not having `rubocop-rspec`. Adding this gem made it work, but I saw, that `rubocop-rspec`  already has `rubocop-rspec_rails` as dependency. Wouldn't it make more sense to suggest `rubocop-rspec` as an extension then? Or should `rubocop-rspec_rails` depend on `rubocop-rspec`? I find it also a bit confusing that https://github.com/rubocop/rubocop-rspec does not mention the extracted cops in the README at all.
 
```
> bundle exec rubocop -V
1.63.5 (using Parser 3.3.1.0, rubocop-ast 1.31.3, running on ruby 3.3.1) [arm64-darwin23]
  - rubocop-performance 1.21.0
  - rubocop-rails 2.24.1
  - rubocop-rspec_rails 2.28.3
```

**Comment by pirj** [comment]
Thanks for reporting 
Can you please provide a full backtrace for “cannot load such file”?

rubocop-rspec should be suggested if you have rspec in your gemfile. I think it’s a deficiency if it doesn’t when only rspec-rails is in the gemfile. Would you like to contribute this (to the main rubocop repo)?

**Comment by pirj** [comment]
Fixed in https://github.com/rubocop/rubocop/pull/12908#pullrequestreview-2062407567

So far you ought to require rubocop-rspec from your .rubocop.yml for everything to function properly.

We can’t make an explicit dependency on rubocop-rspec, as rubygems complains about a circular dependency.

We plan to untangle the two gems completely in the next major versio s, really soon, hold on!
And please accept my apologies for the inconvenience in the meantime.
